/* parser generated by jison 0.4.18 */
/*
  Returns a Parser object of the following structure:

  Parser: {
    yy: {}
  }

  Parser.prototype: {
    yy: {},
    trace: function(),
    symbols_: {associative list: name ==> number},
    terminals_: {associative list: number ==> name},
    productions_: [...],
    performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate, $$, _$),
    table: [...],
    defaultActions: {...},
    parseError: function(str, hash),
    parse: function(input),

    lexer: {
        EOF: 1,
        parseError: function(str, hash),
        setInput: function(input),
        input: function(),
        unput: function(str),
        more: function(),
        less: function(n),
        pastInput: function(),
        upcomingInput: function(),
        showPosition: function(),
        test_match: function(regex_match_array, rule_index),
        next: function(),
        lex: function(),
        begin: function(condition),
        popState: function(),
        _currentRules: function(),
        topState: function(),
        pushState: function(condition),

        options: {
            ranges: boolean           (optional: true ==> token location info will include a .range[] member)
            flex: boolean             (optional: true ==> flex-like lexing behaviour where the rules are tested exhaustively to find the longest match)
            backtrack_lexer: boolean  (optional: true ==> lexer regexes are tested in order and for each matching regex the action code is invoked; the lexer terminates the scan when a token is returned by the action code)
        },

        performAction: function(yy, yy_, $avoiding_name_collisions, YY_START),
        rules: [...],
        conditions: {associative list: name ==> set},
    }
  }


  token location info (@$, _$, etc.): {
    first_line: n,
    last_line: n,
    first_column: n,
    last_column: n,
    range: [start_number, end_number]       (where the numbers are indexes into the input string, regular zero-based)
  }


  the parseError function receives a 'hash' object with these members for lexer and parser errors: {
    text:        (matched text)
    token:       (the produced terminal token, if any)
    line:        (yylineno)
  }
  while parser (grammar) errors will also provide these members, i.e. parser errors deliver a superset of attributes: {
    loc:         (yylloc)
    expected:    (string describing the set of expected tokens)
    recoverable: (boolean: TRUE when the parser has a error recovery rule available for this particular error)
  }
*/
var gramatica = (function(){
var o=function(k,v,o,l){for(o=o||{},l=k.length;l--;o[k[l]]=v);return o},$V0=[1,10],$V1=[1,15],$V2=[40,46,47],$V3=[1,21],$V4=[1,22],$V5=[1,23],$V6=[1,24],$V7=[1,25],$V8=[1,19],$V9=[1,26],$Va=[6,8,9,10,11,12,13,14,15,16,17,18,19,20,41],$Vb=[6,8,9,10,11,12,13,14,15,16,17,18,19,20,37,41],$Vc=[1,65],$Vd=[1,66],$Ve=[1,67],$Vf=[1,68],$Vg=[1,69];
var parser = {trace: function trace () { },
yy: {},
symbols_: {"error":2,"INIT":3,"DECLARACION":4,"EXPRESIONES":5,"+":6,"MOREMORE":7,"-":8,"*":9,"/":10,"%":11,"**":12,"<=":13,"<":14,">=":15,">":16,"!=":17,"==":18,"||":19,"^":20,"TIPO_DECLARACION":21,"pr_const":22,"pr_let":23,"pr_var":24,"TIPODATO_DECLARACION":25,"pr_int":26,"pr_string":27,"pr_double":28,"pr_char":29,"pr_boolean":30,"EXPRECION_VARIABLE":31,"er_int":32,"er_double":33,"er_string":34,"er_char":35,"er_boolean":36,"er_incremento":37,"MOREMORE_AUX":38,"DECLARACIONES_ID":39,"=":40,";":41,"er_id":42,"pr_new":43,"(":44,"DATOS_PARENTESIS_FUNCION":45,")":46,",":47,"DECLARACION_TIPODATO":48,"DECLARACION_CONDICIONAL":49,"AUXA_IF":50,"pr_else":51,"AUX_PARENTESIS_IF":52,"AUXB_IF":53,"AUX_SPARENTESIS_IF":54,"AUX_IF_F":55,"{":56,"}":57,"pr_if":58,"COMPUERTAS_L":59,"er_comparacion":60,"DECLARACION_SWITCH":61,"pr_switch":62,"INSTRUCCION_CASE":63,"pr_case":64,"AUX_SWITCH":65,"DEFAULT_CASE":66,"CASE_FINAL":67,"pr_default":68,":":69,"INSTRUCCION_BREAK":70,"pr_break":71,"DECLARACION_FOR":72,"pr_for":73,"NO_INT":74,"DECLARACION_WHILE":75,"WHILE_WHILE":76,"pr_do":77,"WHILE_COMPARACION":78,"pr_while":79,"DECLARACION_FUNCION":80,"TIPO_METODO":81,"DECLARACION_TIPO_DATO":82,"pr_void":83,"NADA":84,"DECLARACION_CALL":85,"pr_call":86,"DECLARACION_EXP_VAR":87,"$accept":0,"$end":1},
terminals_: {2:"error",6:"+",8:"-",9:"*",10:"/",11:"%",12:"**",13:"<=",14:"<",15:">=",16:">",17:"!=",18:"==",19:"||",20:"^",22:"pr_const",23:"pr_let",24:"pr_var",26:"pr_int",27:"pr_string",28:"pr_double",29:"pr_char",30:"pr_boolean",32:"er_int",33:"er_double",34:"er_string",35:"er_char",36:"er_boolean",37:"er_incremento",40:"=",41:";",42:"er_id",43:"pr_new",44:"(",46:")",47:",",51:"pr_else",56:"{",57:"}",58:"pr_if",60:"er_comparacion",62:"pr_switch",64:"pr_case",68:"pr_default",69:":",71:"pr_break",73:"pr_for",77:"pr_do",79:"pr_while",83:"pr_void",86:"pr_call"},
productions_: [0,[3,1],[5,3],[5,3],[5,3],[5,3],[5,3],[5,3],[5,3],[5,3],[5,3],[5,3],[5,3],[5,3],[5,3],[5,3],[5,1],[21,1],[21,1],[21,1],[25,1],[25,1],[25,1],[25,1],[25,1],[31,1],[31,1],[31,1],[31,1],[31,1],[7,2],[7,2],[7,1],[38,0],[4,5],[4,9],[4,2],[4,2],[39,3],[39,1],[45,1],[45,1],[48,3],[48,1],[49,3],[49,3],[49,2],[49,2],[52,2],[54,1],[50,2],[50,4],[53,2],[53,4],[55,4],[59,3],[59,1],[61,7],[63,4],[63,1],[66,3],[66,1],[67,3],[67,4],[65,4],[70,1],[70,0],[72,14],[74,1],[74,0],[75,6],[78,1],[78,1],[76,4],[80,7],[81,2],[82,4],[82,2],[82,1],[84,1],[85,6],[87,3],[87,1],[87,1]],
performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate /* action[1] */, $$ /* vstack */, _$ /* lstack */) {
/* this == yyval */

var $0 = $$.length - 1;
switch (yystate) {
case 2:
this.$= new Aritmetica($$[$0-2],$$[$0],ArithmeticOption.MAS, _$[$0-2].first_line, _$[$0-2].first_column)
break;
case 3:
this.$= new Aritmetica($$[$0-2],$$[$0],ArithmeticOption.MENOS, _$[$0-2].first_line, _$[$0-2].first_column)
break;
case 4:
this.$= new Aritmetica($$[$0-2],$$[$0],ArithmeticOption.MULTIPLICACION, _$[$0-2].first_line, _$[$0-2].first_column)
break;
case 5:
this.$= new Aritmetica($$[$0-2],$$[$0],ArithmeticOption.DIVISION, _$[$0-2].first_line, _$[$0-2].first_column)
break;
case 6:
this.$= new Aritmetica($$[$0-2],$$[$0],ArithmeticOption.MODULAR, _$[$0-2].first_line, _$[$0-2].first_column)
break;
case 7:
this.$= new Aritmetica($$[$0-2],$$[$0],ArithmeticOption.ELEVAR, _$[$0-2].first_line, _$[$0-2].first_column)
break;
case 16: case 32:
this.$=$$[$0]
break;
case 25:
this.$=new LiteralVar($$[$0],Type.INT , _$[$0].first_line, _$[$0].first_column)
break;
case 26:
this.$=new LiteralVar($$[$0],Type.DOUBLE , _$[$0].first_line, _$[$0].first_column)
break;
case 27:
this.$=new LiteralVar($$[$0],Type.STRING , _$[$0].first_line, _$[$0].first_column)
break;
case 28:
this.$=new LiteralVar($$[$0],Type.CHAR , _$[$0].first_line, _$[$0].first_column)
break;
case 29:
this.$=new LiteralVar($$[$0],Type.BOLEAN , _$[$0].first_line, _$[$0].first_column)
break;
case 30: case 31:
this.$= tt=incremento($$[$0-1]+$$[$0]);
break;
case 34:


    this.$= new Declaracion(id,tipo,expresion,_$[$0-4].first_line, _$[$0-4].first_column );

break;
case 38: case 39:
this.$=ids.push($$[$0])
break;
}
},
table: [{3:1,4:2,21:3,22:[1,6],23:[1,7],24:[1,8],37:[1,5],42:[1,4]},{1:[3]},{1:[2,1]},{39:9,42:$V0},{37:[1,12],39:11,42:$V0},{42:[1,13]},{42:[2,17]},{42:[2,18]},{42:[2,19]},{40:[1,14],47:$V1},o($V2,[2,39]),{40:[1,16],47:$V1},{1:[2,36]},{1:[2,37]},{5:17,7:18,31:20,32:$V3,33:$V4,34:$V5,35:$V6,36:$V7,37:$V8},{42:$V9},{43:[1,27]},{6:[1,29],8:[1,30],9:[1,31],10:[1,32],11:[1,33],12:[1,34],13:[1,35],14:[1,36],15:[1,37],16:[1,38],17:[1,39],18:[1,40],19:[1,41],20:[1,42],41:[1,28]},o($Va,[2,16]),{31:43,32:$V3,33:$V4,34:$V5,35:$V6,36:$V7},o($Va,[2,32],{37:[1,44]}),o($Vb,[2,25]),o($Vb,[2,26]),o($Vb,[2,27]),o($Vb,[2,28]),o($Vb,[2,29]),o($V2,[2,38]),{42:[1,45]},{1:[2,34]},{7:46,31:20,32:$V3,33:$V4,34:$V5,35:$V6,36:$V7,37:$V8},{7:47,31:20,32:$V3,33:$V4,34:$V5,35:$V6,36:$V7,37:$V8},{7:48,31:20,32:$V3,33:$V4,34:$V5,35:$V6,36:$V7,37:$V8},{7:49,31:20,32:$V3,33:$V4,34:$V5,35:$V6,36:$V7,37:$V8},{7:50,31:20,32:$V3,33:$V4,34:$V5,35:$V6,36:$V7,37:$V8},{7:51,31:20,32:$V3,33:$V4,34:$V5,35:$V6,36:$V7,37:$V8},{7:52,31:20,32:$V3,33:$V4,34:$V5,35:$V6,36:$V7,37:$V8},{7:53,31:20,32:$V3,33:$V4,34:$V5,35:$V6,36:$V7,37:$V8},{7:54,31:20,32:$V3,33:$V4,34:$V5,35:$V6,36:$V7,37:$V8},{7:55,31:20,32:$V3,33:$V4,34:$V5,35:$V6,36:$V7,37:$V8},{7:56,31:20,32:$V3,33:$V4,34:$V5,35:$V6,36:$V7,37:$V8},{7:57,31:20,32:$V3,33:$V4,34:$V5,35:$V6,36:$V7,37:$V8},{7:58,31:20,32:$V3,33:$V4,34:$V5,35:$V6,36:$V7,37:$V8},{7:59,31:20,32:$V3,33:$V4,34:$V5,35:$V6,36:$V7,37:$V8},o($Va,[2,30]),o($Va,[2,31]),{44:[1,60]},o($Va,[2,2]),o($Va,[2,3]),o($Va,[2,4]),o($Va,[2,5]),o($Va,[2,6]),o($Va,[2,7]),o($Va,[2,8]),o($Va,[2,9]),o($Va,[2,10]),o($Va,[2,11]),o($Va,[2,12]),o($Va,[2,13]),o($Va,[2,14]),o($Va,[2,15]),{25:64,26:$Vc,27:$Vd,28:$Ve,29:$Vf,30:$Vg,39:62,42:$V0,45:61,48:63},{46:[1,70]},{46:[2,40],47:[1,71]},{46:[2,41]},{46:[2,43]},{46:[2,20]},{46:[2,21]},{46:[2,22]},{46:[2,23]},{46:[2,24]},{41:[1,72]},{25:73,26:$Vc,27:$Vd,28:$Ve,29:$Vf,30:$Vg,42:$V9},{1:[2,35]},{46:[2,42]}],
defaultActions: {2:[2,1],6:[2,17],7:[2,18],8:[2,19],12:[2,36],13:[2,37],28:[2,34],63:[2,41],64:[2,43],65:[2,20],66:[2,21],67:[2,22],68:[2,23],69:[2,24],72:[2,35],73:[2,42]},
parseError: function parseError (str, hash) {
    if (hash.recoverable) {
        this.trace(str);
    } else {
        var error = new Error(str);
        error.hash = hash;
        throw error;
    }
},
parse: function parse(input) {
    var self = this, stack = [0], tstack = [], vstack = [null], lstack = [], table = this.table, yytext = '', yylineno = 0, yyleng = 0, recovering = 0, TERROR = 2, EOF = 1;
    var args = lstack.slice.call(arguments, 1);
    var lexer = Object.create(this.lexer);
    var sharedState = { yy: {} };
    for (var k in this.yy) {
        if (Object.prototype.hasOwnProperty.call(this.yy, k)) {
            sharedState.yy[k] = this.yy[k];
        }
    }
    lexer.setInput(input, sharedState.yy);
    sharedState.yy.lexer = lexer;
    sharedState.yy.parser = this;
    if (typeof lexer.yylloc == 'undefined') {
        lexer.yylloc = {};
    }
    var yyloc = lexer.yylloc;
    lstack.push(yyloc);
    var ranges = lexer.options && lexer.options.ranges;
    if (typeof sharedState.yy.parseError === 'function') {
        this.parseError = sharedState.yy.parseError;
    } else {
        this.parseError = Object.getPrototypeOf(this).parseError;
    }
    function popStack(n) {
        stack.length = stack.length - 2 * n;
        vstack.length = vstack.length - n;
        lstack.length = lstack.length - n;
    }
    _token_stack:
        var lex = function () {
            var token;
            token = lexer.lex() || EOF;
            if (typeof token !== 'number') {
                token = self.symbols_[token] || token;
            }
            return token;
        };
    var symbol, preErrorSymbol, state, action, a, r, yyval = {}, p, len, newState, expected;
    while (true) {
        state = stack[stack.length - 1];
        if (this.defaultActions[state]) {
            action = this.defaultActions[state];
        } else {
            if (symbol === null || typeof symbol == 'undefined') {
                symbol = lex();
            }
            action = table[state] && table[state][symbol];
        }
                    if (typeof action === 'undefined' || !action.length || !action[0]) {
                var errStr = '';
                expected = [];
                for (p in table[state]) {
                    if (this.terminals_[p] && p > TERROR) {
                        expected.push('\'' + this.terminals_[p] + '\'');
                    }
                }
                if (lexer.showPosition) {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ':\n' + lexer.showPosition() + '\nExpecting ' + expected.join(', ') + ', got \'' + (this.terminals_[symbol] || symbol) + '\'';
                } else {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ': Unexpected ' + (symbol == EOF ? 'end of input' : '\'' + (this.terminals_[symbol] || symbol) + '\'');
                }
                this.parseError(errStr, {
                    text: lexer.match,
                    token: this.terminals_[symbol] || symbol,
                    line: lexer.yylineno,
                    loc: yyloc,
                    expected: expected
                });
            }
        if (action[0] instanceof Array && action.length > 1) {
            throw new Error('Parse Error: multiple actions possible at state: ' + state + ', token: ' + symbol);
        }
        switch (action[0]) {
        case 1:
            stack.push(symbol);
            vstack.push(lexer.yytext);
            lstack.push(lexer.yylloc);
            stack.push(action[1]);
            symbol = null;
            if (!preErrorSymbol) {
                yyleng = lexer.yyleng;
                yytext = lexer.yytext;
                yylineno = lexer.yylineno;
                yyloc = lexer.yylloc;
                if (recovering > 0) {
                    recovering--;
                }
            } else {
                symbol = preErrorSymbol;
                preErrorSymbol = null;
            }
            break;
        case 2:
            len = this.productions_[action[1]][1];
            yyval.$ = vstack[vstack.length - len];
            yyval._$ = {
                first_line: lstack[lstack.length - (len || 1)].first_line,
                last_line: lstack[lstack.length - 1].last_line,
                first_column: lstack[lstack.length - (len || 1)].first_column,
                last_column: lstack[lstack.length - 1].last_column
            };
            if (ranges) {
                yyval._$.range = [
                    lstack[lstack.length - (len || 1)].range[0],
                    lstack[lstack.length - 1].range[1]
                ];
            }
            r = this.performAction.apply(yyval, [
                yytext,
                yyleng,
                yylineno,
                sharedState.yy,
                action[1],
                vstack,
                lstack
            ].concat(args));
            if (typeof r !== 'undefined') {
                return r;
            }
            if (len) {
                stack = stack.slice(0, -1 * len * 2);
                vstack = vstack.slice(0, -1 * len);
                lstack = lstack.slice(0, -1 * len);
            }
            stack.push(this.productions_[action[1]][0]);
            vstack.push(yyval.$);
            lstack.push(yyval._$);
            newState = table[stack[stack.length - 2]][stack[stack.length - 1]];
            stack.push(newState);
            break;
        case 3:
            return true;
        }
    }
    return true;
}};

    //codigo en JS
    //importaciones y declaraciones
    //const {} = require('');
    const {Aritmetica} = require('../Tipos/matetica');
    const {LiteralVar} = require('../Tipos/literalVar');
    const {incremento}= require('../funcionesEx/incremento');
    let ids=[]
/* generated by jison-lex 0.3.4 */
var lexer = (function(){
var lexer = ({

EOF:1,

parseError:function parseError(str, hash) {
        if (this.yy.parser) {
            this.yy.parser.parseError(str, hash);
        } else {
            throw new Error(str);
        }
    },

// resets the lexer, sets new input
setInput:function (input, yy) {
        this.yy = yy || this.yy || {};
        this._input = input;
        this._more = this._backtrack = this.done = false;
        this.yylineno = this.yyleng = 0;
        this.yytext = this.matched = this.match = '';
        this.conditionStack = ['INITIAL'];
        this.yylloc = {
            first_line: 1,
            first_column: 0,
            last_line: 1,
            last_column: 0
        };
        if (this.options.ranges) {
            this.yylloc.range = [0,0];
        }
        this.offset = 0;
        return this;
    },

// consumes and returns one char from the input
input:function () {
        var ch = this._input[0];
        this.yytext += ch;
        this.yyleng++;
        this.offset++;
        this.match += ch;
        this.matched += ch;
        var lines = ch.match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno++;
            this.yylloc.last_line++;
        } else {
            this.yylloc.last_column++;
        }
        if (this.options.ranges) {
            this.yylloc.range[1]++;
        }

        this._input = this._input.slice(1);
        return ch;
    },

// unshifts one char (or a string) into the input
unput:function (ch) {
        var len = ch.length;
        var lines = ch.split(/(?:\r\n?|\n)/g);

        this._input = ch + this._input;
        this.yytext = this.yytext.substr(0, this.yytext.length - len);
        //this.yyleng -= len;
        this.offset -= len;
        var oldLines = this.match.split(/(?:\r\n?|\n)/g);
        this.match = this.match.substr(0, this.match.length - 1);
        this.matched = this.matched.substr(0, this.matched.length - 1);

        if (lines.length - 1) {
            this.yylineno -= lines.length - 1;
        }
        var r = this.yylloc.range;

        this.yylloc = {
            first_line: this.yylloc.first_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.first_column,
            last_column: lines ?
                (lines.length === oldLines.length ? this.yylloc.first_column : 0)
                 + oldLines[oldLines.length - lines.length].length - lines[0].length :
              this.yylloc.first_column - len
        };

        if (this.options.ranges) {
            this.yylloc.range = [r[0], r[0] + this.yyleng - len];
        }
        this.yyleng = this.yytext.length;
        return this;
    },

// When called from action, caches matched text and appends it on next action
more:function () {
        this._more = true;
        return this;
    },

// When called from action, signals the lexer that this rule fails to match the input, so the next matching rule (regex) should be tested instead.
reject:function () {
        if (this.options.backtrack_lexer) {
            this._backtrack = true;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. You can only invoke reject() in the lexer when the lexer is of the backtracking persuasion (options.backtrack_lexer = true).\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });

        }
        return this;
    },

// retain first n characters of the match
less:function (n) {
        this.unput(this.match.slice(n));
    },

// displays already matched input, i.e. for error messages
pastInput:function () {
        var past = this.matched.substr(0, this.matched.length - this.match.length);
        return (past.length > 20 ? '...':'') + past.substr(-20).replace(/\n/g, "");
    },

// displays upcoming input, i.e. for error messages
upcomingInput:function () {
        var next = this.match;
        if (next.length < 20) {
            next += this._input.substr(0, 20-next.length);
        }
        return (next.substr(0,20) + (next.length > 20 ? '...' : '')).replace(/\n/g, "");
    },

// displays the character position where the lexing error occurred, i.e. for error messages
showPosition:function () {
        var pre = this.pastInput();
        var c = new Array(pre.length + 1).join("-");
        return pre + this.upcomingInput() + "\n" + c + "^";
    },

// test the lexed token: return FALSE when not a match, otherwise return token
test_match:function(match, indexed_rule) {
        var token,
            lines,
            backup;

        if (this.options.backtrack_lexer) {
            // save context
            backup = {
                yylineno: this.yylineno,
                yylloc: {
                    first_line: this.yylloc.first_line,
                    last_line: this.last_line,
                    first_column: this.yylloc.first_column,
                    last_column: this.yylloc.last_column
                },
                yytext: this.yytext,
                match: this.match,
                matches: this.matches,
                matched: this.matched,
                yyleng: this.yyleng,
                offset: this.offset,
                _more: this._more,
                _input: this._input,
                yy: this.yy,
                conditionStack: this.conditionStack.slice(0),
                done: this.done
            };
            if (this.options.ranges) {
                backup.yylloc.range = this.yylloc.range.slice(0);
            }
        }

        lines = match[0].match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno += lines.length;
        }
        this.yylloc = {
            first_line: this.yylloc.last_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.last_column,
            last_column: lines ?
                         lines[lines.length - 1].length - lines[lines.length - 1].match(/\r?\n?/)[0].length :
                         this.yylloc.last_column + match[0].length
        };
        this.yytext += match[0];
        this.match += match[0];
        this.matches = match;
        this.yyleng = this.yytext.length;
        if (this.options.ranges) {
            this.yylloc.range = [this.offset, this.offset += this.yyleng];
        }
        this._more = false;
        this._backtrack = false;
        this._input = this._input.slice(match[0].length);
        this.matched += match[0];
        token = this.performAction.call(this, this.yy, this, indexed_rule, this.conditionStack[this.conditionStack.length - 1]);
        if (this.done && this._input) {
            this.done = false;
        }
        if (token) {
            return token;
        } else if (this._backtrack) {
            // recover context
            for (var k in backup) {
                this[k] = backup[k];
            }
            return false; // rule action called reject() implying the next rule should be tested instead.
        }
        return false;
    },

// return next match in input
next:function () {
        if (this.done) {
            return this.EOF;
        }
        if (!this._input) {
            this.done = true;
        }

        var token,
            match,
            tempMatch,
            index;
        if (!this._more) {
            this.yytext = '';
            this.match = '';
        }
        var rules = this._currentRules();
        for (var i = 0; i < rules.length; i++) {
            tempMatch = this._input.match(this.rules[rules[i]]);
            if (tempMatch && (!match || tempMatch[0].length > match[0].length)) {
                match = tempMatch;
                index = i;
                if (this.options.backtrack_lexer) {
                    token = this.test_match(tempMatch, rules[i]);
                    if (token !== false) {
                        return token;
                    } else if (this._backtrack) {
                        match = false;
                        continue; // rule action called reject() implying a rule MISmatch.
                    } else {
                        // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
                        return false;
                    }
                } else if (!this.options.flex) {
                    break;
                }
            }
        }
        if (match) {
            token = this.test_match(match, rules[index]);
            if (token !== false) {
                return token;
            }
            // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
            return false;
        }
        if (this._input === "") {
            return this.EOF;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. Unrecognized text.\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });
        }
    },

// return next match that has a token
lex:function lex () {
        var r = this.next();
        if (r) {
            return r;
        } else {
            return this.lex();
        }
    },

// activates a new lexer condition state (pushes the new lexer condition state onto the condition stack)
begin:function begin (condition) {
        this.conditionStack.push(condition);
    },

// pop the previously active lexer condition state off the condition stack
popState:function popState () {
        var n = this.conditionStack.length - 1;
        if (n > 0) {
            return this.conditionStack.pop();
        } else {
            return this.conditionStack[0];
        }
    },

// produce the lexer rule set which is active for the currently active lexer condition state
_currentRules:function _currentRules () {
        if (this.conditionStack.length && this.conditionStack[this.conditionStack.length - 1]) {
            return this.conditions[this.conditionStack[this.conditionStack.length - 1]].rules;
        } else {
            return this.conditions["INITIAL"].rules;
        }
    },

// return the currently active lexer condition state; when an index argument is provided it produces the N-th previous condition state, if available
topState:function topState (n) {
        n = this.conditionStack.length - 1 - Math.abs(n || 0);
        if (n >= 0) {
            return this.conditionStack[n];
        } else {
            return "INITIAL";
        }
    },

// alias for begin(condition)
pushState:function pushState (condition) {
        this.begin(condition);
    },

// return the number of states currently on the stack
stateStackSize:function stateStackSize() {
        return this.conditionStack.length;
    },
options: {"case-insensitive":true},
performAction: function anonymous(yy,yy_,$avoiding_name_collisions,YY_START) {
var YYSTATE=YY_START;
switch($avoiding_name_collisions) {
case 0:/* skip whitespace */
break;
case 1:// comentario simple línea
break;
case 2:// comentario multiple líneas
break;
case 3:return 33
break;
case 4:return 32
break;
case 5:return 35
break;
case 6:return 36
break;
case 7:return 34
break;
case 8:return 42
break;
case 9:return 37
break;
case 10:return 26
break;
case 11:return 27
break;
case 12:return 28
break;
case 13:return 30
break;
case 14:return 29
break;
case 15:return 22
break;
case 16:return 23
break;
case 17:return 24
break;
case 18:return 58
break;
case 19:return 51
break;
case 20:return 62
break;
case 21:return 64
break;
case 22:return 71
break;
case 23:return 73
break;
case 24:return 79
break;
case 25:return 77
break;
case 26:return 'pr_continue'
break;
case 27:return 83
break;
case 28:return 86
break;
case 29:return 'pr_return'
break;
case 30:return 'pr_println'
break;
case 31:return 'pr_print'
break;
case 32:return 'pr_type'
break;
case 33:return 43
break;
case 34:return 68
break;
case 35:return 6
break;
case 36:return 8
break;
case 37:return 9
break;
case 38:return 6
break;
case 39:return 10
break;
case 40:return 11
break;
case 41:return 12
break;
case 42:return 13
break;
case 43:return 14
break;
case 44:return 15
break;
case 45:return 16
break;
case 46:return 17
break;
case 47:return 18
break;
case 48:return 19
break;
case 49:return '&&'
break;
case 50:return 20
break;
case 51:return 47
break;
case 52:return 44
break;
case 53:return 46
break;
case 54:return 56
break;
case 55:return 57
break;
case 56:return 69
break;
case 57:return 40
break;
case 58:return 'EOF'
break;
case 59: 
        console.log("error lexico :"+yy_.yytext)
        //push para array errores
    
break;
}
},
rules: [/^(?:\s+)/i,/^(?:\/\/.*)/i,/^(?:[/][*][^*]*[*]+([^/*][^*]*[*]+)*[/])/i,/^(?:([-]?[0-9]*[\.][0-9]+))/i,/^(?:([-]?[0-9]+))/i,/^(?:([\'][^\']?[\']))/i,/^(?:(true|false\b))/i,/^(?:([\"][^\"]*[\\\"]*[\"]))/i,/^(?:([a-zA-Z0-9ñÑ][a-zA-Z0-9ñÑ_]*))/i,/^(?:([\-\-]|[\+\+]))/i,/^(?:int\b)/i,/^(?:string\b)/i,/^(?:double\b)/i,/^(?:boolean\b)/i,/^(?:char\b)/i,/^(?:const\b)/i,/^(?:let\b)/i,/^(?:var\b)/i,/^(?:if\b)/i,/^(?:else\b)/i,/^(?:switch\b)/i,/^(?:case\b)/i,/^(?:break\b)/i,/^(?:for\b)/i,/^(?:while\b)/i,/^(?:do\b)/i,/^(?:continue\b)/i,/^(?:void\b)/i,/^(?:call\b)/i,/^(?:return\b)/i,/^(?:println\b)/i,/^(?:print\b)/i,/^(?:type\b)/i,/^(?:new\b)/i,/^(?:default\b)/i,/^(?:\+)/i,/^(?:-)/i,/^(?:\*)/i,/^(?:\+)/i,/^(?:\/)/i,/^(?:%)/i,/^(?:\*\*)/i,/^(?:<=)/i,/^(?:<)/i,/^(?:>=)/i,/^(?:>)/i,/^(?:!=)/i,/^(?:==)/i,/^(?:\|\|)/i,/^(?:&&)/i,/^(?:\^)/i,/^(?:,)/i,/^(?:\()/i,/^(?:\))/i,/^(?:\{)/i,/^(?:\})/i,/^(?::)/i,/^(?:=)/i,/^(?:$)/i,/^(?:.)/i],
conditions: {"INITIAL":{"rules":[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59],"inclusive":true}}
});
return lexer;
})();
parser.lexer = lexer;
function Parser () {
  this.yy = {};
}
Parser.prototype = parser;parser.Parser = Parser;
return new Parser;
})();


if (typeof require !== 'undefined' && typeof exports !== 'undefined') {
exports.parser = gramatica;
exports.Parser = gramatica.Parser;
exports.parse = function () { return gramatica.parse.apply(gramatica, arguments); };
exports.main = function commonjsMain (args) {
    if (!args[1]) {
        console.log('Usage: '+args[0]+' FILE');
        process.exit(1);
    }
    var source = require('fs').readFileSync(require('path').normalize(args[1]), "utf8");
    return exports.parser.parse(source);
};
if (typeof module !== 'undefined' && require.main === module) {
  exports.main(process.argv.slice(1));
}
}